### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by pfink** [lejonet/systemd-networkd#1]
Hi lejonet,

found your nice ansible module here, thanks for sharing it on GitHub! I'd like to use it and add support for macvlan bridges. Could you add some usage examples for this module? This would it make easier for me getting in ;-)

Thanks,
Patrick

**Comment by lejonet** [comment]
That sounds great!

Examples are next on my todo list, I hope to have time to write them today or tomorrow.
I look forward to seeing your pull request :D

**Comment by pfink** [comment]
Do you have some time today or tomorrow? Otherwise I'd have to start without examples :(

**Comment by lejonet** [comment]
I'm sorry that it took a while, real life stuff that came inbetween, but I've now pushed the commits that contained the documentation and examples in the README too

**Comment by pfink** [comment]
Great, thank you!
